<pipeline> ::= <contributor_root>
<contributor_root> ::= c_lcl_flow_contributor <empty_pipeline> <sorted_pipeline>
<empty_pipeline> ::= noop
<sorted_pipeline> ::= <ordinary_operator> | <ordinary_operator> <sorted_pipeline> | <timestamp_sensitive_operator> | <timestamp_sensitive_operator> <sorted_pipeline> | <sorted_fork> | <sorted_fork> <unsorted_pipeline>
<unsorted_pipeline> ::= <ordinary_operator> | <ordinary_operator> <unsorted_pipeline> | <unsorted_fork> | <unsorted_fork> <unsorted_pipeline>
<ordinary_operator> ::= <filter_discrete_numeric> | <filter_continuous_numeric> | <filter_nominal> | <filter_query_condition> | <map_duplicate> | <map_aggregate_discrete_numeric> | <map_aggregate_continuous_numeric> | <map_condition_preserving_noise_nominal> | <map_condition_preserving_noise_discrete_numeric> | <map_condition_preserving_noise_continuous_numeric> | <map_condition_preserving_rir_nominal> | <map_condition_preserving_rir_discrete_numeric> | <map_condition_preserving_rir_continuous_numeric>
<timestamp_sensitive_operator> ::= <map_condition_pairwise_swap_nominal> | <map_condition_pairwise_swap_discrete_numeric> | <map_condition_pairwise_swap_continuous_numeric> | <map_condition_partition_shuffle_nominal> | <map_condition_partition_shuffle_discrete_numeric> | <map_condition_partition_shuffle_continuous_numeric>
<sorted_fork> ::= <fork_discrete_numeric_sorted> | <fork_continuous_numeric_sorted> | <fork_nominal_sorted> | <query_condition_fork_sorted>
<unsorted_fork> ::= <fork_discrete_numeric_unsorted> | <fork_continuous_numeric_unsorted> | <fork_nominal_unsorted> | <query_condition_fork_unsorted>
<filter_discrete_numeric> ::= <discrete_numeric_attribute> <numeric_condition> <numeric_value>
<filter_continuous_numeric> ::= <continuous_numeric_attribute> <numeric_condition> <numeric_value>
<filter_nominal> ::= f1 <nominal_condition> <f1_value>
<filter_query_condition> ::= <query_condition> <condition_keep>
<map_duplicate> ::= <probability>
<map_aggregate_discrete_numeric> ::= <discrete_numeric_attribute> <numeric_agg_fun> <window_size>
<map_aggregate_continuous_numeric> ::= <continuous_numeric_attribute> <numeric_agg_fun> <window_size>
<map_condition_preserving_noise_nominal> ::= <nominal_attribute> <probability> <query_condition>
<map_condition_preserving_noise_discrete_numeric> ::= <discrete_numeric_attribute> <percentage> <query_condition>
<map_condition_preserving_noise_continuous_numeric> ::= <continuous_numeric_attribute> <percentage> <query_condition>
<map_condition_preserving_rir_nominal> ::= <nominal_attribute> <query_condition>
<map_condition_preserving_rir_discrete_numeric> ::= <discrete_numeric_attribute> <query_condition>
<map_condition_preserving_rir_continuous_numeric> ::= <continuous_numeric_attribute> <query_condition>
<map_condition_pairwise_swap_nominal> ::= <nominal_attribute> <query_condition>
<map_condition_pairwise_swap_discrete_numeric> ::= <discrete_numeric_attribute> <query_condition>
<map_condition_pairwise_swap_continuous_numeric> ::= <continuous_numeric_attribute> <query_condition>
<map_condition_partition_shuffle_nominal> ::= <nominal_attribute> <query_condition>
<map_condition_partition_shuffle_discrete_numeric> ::= <discrete_numeric_attribute> <query_condition>
<map_condition_partition_shuffle_continuous_numeric> ::= <continuous_numeric_attribute> <query_condition>
<fork_discrete_numeric_sorted> ::= <discrete_numeric_attribute> <numeric_condition> <numeric_value> <sorted_pipeline> <sorted_pipeline>
<fork_continuous_numeric_sorted> ::= <continuous_numeric_attribute> <numeric_condition> <numeric_value> <sorted_pipeline> <sorted_pipeline>
<fork_nominal_sorted> ::= f1 <nominal_condition> <f1_value> <sorted_pipeline> <sorted_pipeline>
<query_condition_fork_sorted> ::= <query_condition> <sorted_pipeline> <sorted_pipeline>
<fork_discrete_numeric_unsorted> ::= <discrete_numeric_attribute> <numeric_condition> <numeric_value> <unsorted_pipeline> <unsorted_pipeline>
<fork_continuous_numeric_unsorted> ::= <continuous_numeric_attribute> <numeric_condition> <numeric_value> <unsorted_pipeline> <unsorted_pipeline>
<fork_nominal_unsorted> ::= f1 <nominal_condition> <f1_value> <unsorted_pipeline> <unsorted_pipeline>
<query_condition_fork_unsorted> ::= <query_condition> <unsorted_pipeline> <unsorted_pipeline>
<query_condition> ::= c_lcl_flow_contributor | c_f2_ge_1_0 | c_f11_lt_45 | c_f1_eq_0 | c_f10_between_34_45
<condition_keep> ::= keep_true | keep_false
<nominal_attribute> ::= f1
<discrete_numeric_attribute> ::= f10 | f11
<continuous_numeric_attribute> ::= f2 | f3 | f4 | f5 | f6 | f7 | f8 | f9
<f1_value> ::= 0 | 1
<nominal_condition> ::= eq | neq
<numeric_condition> ::= lt | gt
<numeric_value> ::= urir | drir
<numeric_agg_fun> ::= min | avg | max
<window_size> ::= 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10
<percentage> ::= 0.01 | 0.05 | 0.10 | 0.25
<probability> ::= 0.1 | 0.2 | 0.3 | 0.4 | 0.5 | 0.6 | 0.7 | 0.8 | 0.9 | 1.0
