status = error
name = ThesisLoggingConfig

appender.Console.type = Console
appender.Console.name = Console
appender.Console.layout.type = PatternLayout
appender.Console.layout.pattern = %d{HH:mm:ss.SSS} %-5level %c - %msg%n

rootLogger.level = INFO
rootLogger.appenderRefs = stdout
rootLogger.appenderRef.stdout.ref = Console

logger.jgea.name = jgea
logger.jgea.level = INFO

logger.query.name = query
logger.query.level = ERROR

logger.component.name = component
logger.component.level = ERROR

logger.scheduling.name = scheduling
logger.scheduling.level = ERROR

logger.liebre.name = com.vincenzogulisano
logger.liebre.level = ERROR

logger.jgeaFramework.name = io.github.ericmedvet
logger.jgeaFramework.level = ERROR
