<pipeline> ::= <operator> | <operator> <pipeline>
<operator> ::= <filter>
<filter> ::= <attribute> <condition> <value>
<attribute> ::= 'avg_X' | 'avg_Y'
<condition> ::= lt | gt
<value> ::= <dig> . <dig> <dig> E <sign> <dig>
<dig> ::= 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9
<sign> ::= + | -
