<pipeline> ::= <contributor_root>
<contributor_root> ::= <sorted_pipeline> <sorted_pipeline>
<sorted_pipeline> ::= <ordinary_operator> | <ordinary_operator> <sorted_pipeline> | <timestamp_sensitive_operator> | <timestamp_sensitive_operator> <sorted_pipeline> | <sorted_fork> | <sorted_fork> <unsorted_pipeline>
<unsorted_pipeline> ::= <ordinary_operator> | <ordinary_operator> <unsorted_pipeline> | <unsorted_fork> | <unsorted_fork> <unsorted_pipeline>
<ordinary_operator> ::= <filter_continuous_numeric> | <filter_query_condition> | <map_duplicate> | <map_noise_continuous_numeric> | <map_rir_continuous_numeric> | <map_aggregate_continuous_numeric> | <map_condition_preserving_noise_continuous_numeric> | <map_condition_preserving_rir_continuous_numeric>
<timestamp_sensitive_operator> ::= <map_timestamp_pairwise_swap_continuous_numeric> | <map_timestamp_group_shuffle_continuous_numeric> | <map_condition_pairwise_swap_continuous_numeric> | <map_condition_partition_shuffle_continuous_numeric>
<sorted_fork> ::= <fork_continuous_numeric_sorted> | <query_condition_fork_sorted>
<unsorted_fork> ::= <fork_continuous_numeric_unsorted> | <query_condition_fork_unsorted>
<filter_continuous_numeric> ::= <continuous_numeric_attribute> <numeric_condition> <numeric_value>
<filter_query_condition> ::= <condition_keep>
<map_duplicate> ::= <probability>
<map_noise_continuous_numeric> ::= <continuous_numeric_attribute> <percentage>
<map_rir_continuous_numeric> ::= <continuous_numeric_attribute>
<map_aggregate_continuous_numeric> ::= <continuous_numeric_attribute> <numeric_agg_fun> <window_size>
<map_condition_preserving_noise_continuous_numeric> ::= <continuous_numeric_attribute> <percentage>
<map_condition_preserving_rir_continuous_numeric> ::= <continuous_numeric_attribute>
<map_timestamp_pairwise_swap_continuous_numeric> ::= <continuous_numeric_attribute>
<map_timestamp_group_shuffle_continuous_numeric> ::= <continuous_numeric_attribute>
<map_condition_pairwise_swap_continuous_numeric> ::= <continuous_numeric_attribute>
<map_condition_partition_shuffle_continuous_numeric> ::= <continuous_numeric_attribute>
<fork_continuous_numeric_sorted> ::= <continuous_numeric_attribute> <numeric_condition> <numeric_value> <sorted_pipeline> <sorted_pipeline>
<query_condition_fork_sorted> ::= <sorted_pipeline> <sorted_pipeline>
<fork_continuous_numeric_unsorted> ::= <continuous_numeric_attribute> <numeric_condition> <numeric_value> <unsorted_pipeline> <unsorted_pipeline>
<query_condition_fork_unsorted> ::= <unsorted_pipeline> <unsorted_pipeline>
<condition_keep> ::= keep_true | keep_false
<continuous_numeric_attribute> ::= f1 | f2
<numeric_condition> ::= lt | gt
<numeric_value> ::= urir | drir
<numeric_agg_fun> ::= min | avg | max
<window_size> ::= 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10
<percentage> ::= 0.01 | 0.05 | 0.10 | 0.25
<probability> ::= 0.1 | 0.2 | 0.3 | 0.4 | 0.5 | 0.6 | 0.7 | 0.8 | 0.9 | 1.0
