<pipeline> ::= <operator> | <operator> <pipeline>
<operator> ::= <filter> | <map_duplicate> | <map_noise> | <map_aggregate> | <map_rir> | <fork_ops_join>
<filter> ::= <attribute> <condition> <value>
<map_duplicate> ::= <probability>
<map_noise> ::= <attribute> <percentage>
<map_aggregate> ::= <attribute> <agg_fun> <window_size>
<map_rir> ::= <attribute>
<fork_ops_join> ::= <pipeline> <pipeline>
<attribute> ::= f1 | f2 | f3 | f4 | f5 | f6
<condition> ::= lt | gt
<value> ::= urir | drir
<agg_fun> ::= min | avg | max
<window_size> ::= 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10
<probability> ::= 0.01 | 0.02 | 0.03 | 0.04 | 0.05
<percentage> ::= 0.01 | 0.05 | 0.10 | 0.25
